#############################################################################
# Makefile for building: appBuilder
# Generated by qmake (2.01a) (Qt 4.8.1) on: czw. gru 12 23:11:54 2013
# Project:  appBuilder.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile appBuilder.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/AppGUI.cpp \
		src/models/Person.cpp \
		src/models/Mail.cpp \
		src/models/Headers.cpp \
		src/models/Email.cpp \
		src/models/Graph.cpp \
		src/views/settingswindow.cpp \
		src/views/mainwindow.cpp \
		src/views/loadfilewindow.cpp \
		src/views/helpwindow.cpp \
		src/utils/GenericException.cpp \
		src/views/graphspace.cpp \
		src/controllers/parser.cpp moc_settingswindow.cpp \
		moc_mainwindow.cpp \
		moc_loadfilewindow.cpp \
		moc_helpwindow.cpp \
		moc_graphspace.cpp \
		qrc_images.cpp
OBJECTS       = AppGUI.o \
		Person.o \
		Mail.o \
		Headers.o \
		Email.o \
		Graph.o \
		settingswindow.o \
		mainwindow.o \
		loadfilewindow.o \
		helpwindow.o \
		GenericException.o \
		graphspace.o \
		parser.o \
		moc_settingswindow.o \
		moc_mainwindow.o \
		moc_loadfilewindow.o \
		moc_helpwindow.o \
		moc_graphspace.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		appBuilder.pro
QMAKE_TARGET  = appBuilder
DESTDIR       = 
TARGET        = appBuilder

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_settingswindow.h ui_mainwindow.h ui_loadfilewindow.h ui_helpwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: appBuilder.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile appBuilder.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile appBuilder.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/appBuilder1.0.0 || $(MKDIR) .tmp/appBuilder1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/appBuilder1.0.0/ && $(COPY_FILE) --parents src/models/Containers.hpp src/utils/Exceptions.hpp src/views/settingswindow.h src/views/mainwindow.h src/views/loadfilewindow.h src/views/helpwindow.h src/models/Graph.h src/views/graphspace.h .tmp/appBuilder1.0.0/ && $(COPY_FILE) --parents src/assets/images.qrc .tmp/appBuilder1.0.0/ && $(COPY_FILE) --parents src/AppGUI.cpp src/models/Person.cpp src/models/Mail.cpp src/models/Headers.cpp src/models/Email.cpp src/models/Graph.cpp src/views/settingswindow.cpp src/views/mainwindow.cpp src/views/loadfilewindow.cpp src/views/helpwindow.cpp src/utils/GenericException.cpp src/views/graphspace.cpp src/controllers/parser.cpp .tmp/appBuilder1.0.0/ && $(COPY_FILE) --parents src/views/settingswindow.ui src/views/mainwindow.ui src/views/loadfilewindow.ui src/views/helpwindow.ui .tmp/appBuilder1.0.0/ && (cd `dirname .tmp/appBuilder1.0.0` && $(TAR) appBuilder1.0.0.tar appBuilder1.0.0 && $(COMPRESS) appBuilder1.0.0.tar) && $(MOVE) `dirname .tmp/appBuilder1.0.0`/appBuilder1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/appBuilder1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_settingswindow.cpp moc_mainwindow.cpp moc_loadfilewindow.cpp moc_helpwindow.cpp moc_graphspace.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_settingswindow.cpp moc_mainwindow.cpp moc_loadfilewindow.cpp moc_helpwindow.cpp moc_graphspace.cpp
moc_settingswindow.cpp: src/views/settingswindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/views/settingswindow.h -o moc_settingswindow.cpp

moc_mainwindow.cpp: src/views/loadfilewindow.h \
		src/views/helpwindow.h \
		src/views/settingswindow.h \
		src/models/Containers.hpp \
		src/views/graphspace.h \
		src/models/Graph.h \
		src/views/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/views/mainwindow.h -o moc_mainwindow.cpp

moc_loadfilewindow.cpp: src/views/loadfilewindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/views/loadfilewindow.h -o moc_loadfilewindow.cpp

moc_helpwindow.cpp: src/views/helpwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/views/helpwindow.h -o moc_helpwindow.cpp

moc_graphspace.cpp: src/models/Containers.hpp \
		src/models/Graph.h \
		src/views/graphspace.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/views/graphspace.h -o moc_graphspace.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: src/assets/images.qrc \
		src/assets/images/icon2.png \
		src/assets/images/009.png \
		src/assets/images/strzalka.png \
		src/assets/images/32.png \
		src/assets/images/031.png \
		src/assets/images/032.png \
		src/assets/images/001.png \
		src/assets/images/034.png \
		src/assets/images/002.png \
		src/assets/images/003.png \
		src/assets/images/015.png \
		src/assets/images/026.png \
		src/assets/images/037.png \
		src/assets/images/038.png \
		src/assets/images/039.png \
		src/assets/images/icon1.png \
		src/assets/images/picture.png
	/usr/bin/rcc -name images src/assets/images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_settingswindow.h ui_mainwindow.h ui_loadfilewindow.h ui_helpwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_settingswindow.h ui_mainwindow.h ui_loadfilewindow.h ui_helpwindow.h
ui_settingswindow.h: src/views/settingswindow.ui
	/usr/bin/uic-qt4 src/views/settingswindow.ui -o ui_settingswindow.h

ui_mainwindow.h: src/views/mainwindow.ui
	/usr/bin/uic-qt4 src/views/mainwindow.ui -o ui_mainwindow.h

ui_loadfilewindow.h: src/views/loadfilewindow.ui
	/usr/bin/uic-qt4 src/views/loadfilewindow.ui -o ui_loadfilewindow.h

ui_helpwindow.h: src/views/helpwindow.ui
	/usr/bin/uic-qt4 src/views/helpwindow.ui -o ui_helpwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

AppGUI.o: src/AppGUI.cpp src/views/mainwindow.h \
		src/views/loadfilewindow.h \
		src/views/helpwindow.h \
		src/views/settingswindow.h \
		src/models/Containers.hpp \
		src/views/graphspace.h \
		src/models/Graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AppGUI.o src/AppGUI.cpp

Person.o: src/models/Person.cpp src/models/Containers.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Person.o src/models/Person.cpp

Mail.o: src/models/Mail.cpp src/models/Containers.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mail.o src/models/Mail.cpp

Headers.o: src/models/Headers.cpp src/models/Containers.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Headers.o src/models/Headers.cpp

Email.o: src/models/Email.cpp src/models/Containers.hpp \
		src/utils/Exceptions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Email.o src/models/Email.cpp

Graph.o: src/models/Graph.cpp src/models/Graph.h \
		src/models/Containers.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graph.o src/models/Graph.cpp

settingswindow.o: src/views/settingswindow.cpp src/views/settingswindow.h \
		ui_settingswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingswindow.o src/views/settingswindow.cpp

mainwindow.o: src/views/mainwindow.cpp src/views/mainwindow.h \
		src/views/loadfilewindow.h \
		src/views/helpwindow.h \
		src/views/settingswindow.h \
		src/models/Containers.hpp \
		src/views/graphspace.h \
		src/models/Graph.h \
		ui_mainwindow.h \
		ui_loadfilewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/views/mainwindow.cpp

loadfilewindow.o: src/views/loadfilewindow.cpp src/views/loadfilewindow.h \
		ui_loadfilewindow.h \
		src/views/mainwindow.h \
		src/views/helpwindow.h \
		src/views/settingswindow.h \
		src/models/Containers.hpp \
		src/views/graphspace.h \
		src/models/Graph.h \
		src/controllers/parser.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadfilewindow.o src/views/loadfilewindow.cpp

helpwindow.o: src/views/helpwindow.cpp src/views/helpwindow.h \
		ui_helpwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpwindow.o src/views/helpwindow.cpp

GenericException.o: src/utils/GenericException.cpp src/utils/Exceptions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GenericException.o src/utils/GenericException.cpp

graphspace.o: src/views/graphspace.cpp src/views/graphspace.h \
		src/models/Containers.hpp \
		src/models/Graph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphspace.o src/views/graphspace.cpp

parser.o: src/controllers/parser.cpp src/controllers/parser.hpp \
		src/models/Containers.hpp \
		src/utils/Exceptions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o src/controllers/parser.cpp

moc_settingswindow.o: moc_settingswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingswindow.o moc_settingswindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_loadfilewindow.o: moc_loadfilewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadfilewindow.o moc_loadfilewindow.cpp

moc_helpwindow.o: moc_helpwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpwindow.o moc_helpwindow.cpp

moc_graphspace.o: moc_graphspace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphspace.o moc_graphspace.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

